Repository flyingbearxx/SHARKY-SOEN341_Project_F24, pull requests merged in 2024-11, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#8 Update client.js
  Sharky/src/client.js
Labels: backend

#16 Add new components and tests, modify ContactUs.js
  Sharky/src/App.js
  Sharky/src/components/DateTime.js
  Sharky/src/components/Layout.js
  Sharky/src/pages/ContactUs.js
  Sharky/src/test/Confirmpage.test.js
  Sharky/src/test/Logout.test.js
Labels: enhancement, test

#17 Update LICENSE
  LICENSE
Labels: documentation

#21 Raghda sprint3
  Sharky/src/App.js
  Sharky/src/pages/Assessment.js
  Sharky/src/pages/ConceptualAssessment.js
  Sharky/src/pages/Dashboard.js
  Sharky/src/pages/PracticalAssessment.js
  Sharky/src/pages/TeamManagement.js
  Sharky/src/style.css
Labels: enhancement

#22 Create Sharky_Sprint3_meeting9_Nov8.md
  Meeting Minutes/Sharky_Sprint3_meeting9_Nov8.md
Labels: documentation

#24 Acceptance Test for ShowTeams (Student View). Fixes #23
  Sharky/src/test/ShowTeams.test.js
Labels: test

#25 Update Sharky_Sprint3_meeting9_Nov8.md
  Meeting Minutes/Sharky_Sprint3_meeting9_Nov8.md
Labels: documentation

#28 Acceptance test for Handling teams - instructor view
  Sharky/src/pages/HandleTeamInstructor.js
  Sharky/src/pages/main.js
  Sharky/src/test/HandleTeams.test.js
Labels: test

#31 Acceptance test for cooperation dimension of assessment
  Sharky/src/test/assessment.test.js
Labels: test

#36 Ana at resetpw
  Sharky/src/test/Resetpw.test.js
Labels: enhancement, test

#37 Khujista conceptual test
  Sharky/src/pages/Assessment.js
  Sharky/src/test/ConceptualAssessment.test.js
  Sharky/src/test/WorkEthicAssessment.test.js
Labels: test

#35 Khujistasprint3
  Sharky/src/pages/Assessment.js
  Sharky/src/test/WorkEthicAssessment.test.js
Labels: test

#39 Create Sharky_Sprint3_Meeting10_Nov5.md
  Meeting Minutes/Sharky_Sprint3_meeting9_Nov5.md
Labels: documentation

#40 Rename Sharky_Sprint3_meeting9_Nov8.md to Sharky_Sprint3_meeting10_No…
  Meeting Minutes/Sharky_Sprint3_meeting10_Nov8.md
Labels: documentation

#41 removed dashboard from student page
  Sharky/src/pages/Homepage.js
Labels: enhancement

#44 Acceptance test for the SignUp component
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/style.css
  Sharky/src/test/SignUp.test.js
Labels: test

#46 Updated detailed view results and css adjustments
  Sharky/src/pages/Dashboard.js
  Sharky/src/style.css
Labels: enhancement

#47 Create Sharky_Sprint3_meeting11_Nov14.md
  Meeting Minutes/Sharky_Sprint3_meeting11_Nov14.md
Labels: documentation

#49 Fix unescaped apostrophes across multiple pages and install ESLint tool
  Sharky/.eslintrc.json
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/pages/Assessment.js
  Sharky/src/pages/ConceptualAssessment.js
  Sharky/src/pages/ContactUs.js
  Sharky/src/pages/LogIn.js
  Sharky/src/pages/PracticalAssessment.js
  Sharky/src/pages/WorkEthicAssessment.js
Labels: bug

#51 New Enhancement to the Contact Us page
  Sharky/src/pages/ContactUs.js
  Sharky/src/style.css
Labels: enhancement

#64 Enhancement to ShowTeams.test
  Sharky/src/test/ShowTeams.test.js
Labels: bug

#66 Create Sharky_Sprint4_meeting12_Nov22.md
  Meeting Minutes/Sharky_Sprint4_meeting12_Nov22.md
Labels: documentation

#68 CSS improvment to Contact Us page and for the date shown on all pages
  Sharky/src/components/Layout.js
  Sharky/src/style.css
Labels: enhancement

#72 Adding Date/Time component to the Dashboard page
  Sharky/src/App.js
Labels: bug, enhancement

#70 US-41: Additional Feature - Student Profile
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/App.js
  Sharky/src/client.js
  Sharky/src/pages/Homepage.js
  Sharky/src/pages/Profile.js
  Sharky/src/pages/main.js
  Sharky/src/style.css
Labels: enhancement, backend

#73 Raghda course evaluation student
  Sharky/src/App.js
  Sharky/src/pages/Assessment.js
  Sharky/src/pages/CourseEvaluation.js
  Sharky/src/pages/HandleTeamInstructure.js
  Sharky/src/pages/Homepage.js
  Sharky/src/pages/main.js
  Sharky/src/style.css
Labels: enhancement

#75 Deletion of the Assessor column in the Student Assessment Result Pro…
  Sharky/src/pages/Profile.js
Labels: bug

#76 fixed css
  Sharky/src/style.css
Labels: bug

#77 Update style.css
  Sharky/src/style.css
Labels: bug

#78 AT14 - Acceptance Test for Profile.js related to Issue #58
  Sharky/package-lock.json
  Sharky/package.json
  Sharky/src/pages/Profile.js
  Sharky/src/setupTests.js
  Sharky/src/test/Profile.test.js
Labels: test

#81 Instructor can see the course evaluation results + Adjusted CSS
  Sharky/package.json
  Sharky/src/App.js
  Sharky/src/pages/CourseEvaluationResult.js
  Sharky/src/pages/Dashboard.js
  Sharky/src/pages/Homepage.js
  Sharky/src/pages/TeamManagement.js
  Sharky/src/pages/main.js
  Sharky/src/style.css
  Sharky/src/test/CourseEvaluationResult.test.js
Labels: bug, enhancement

#85 Adjusting the css for ContactUs page
  Sharky/src/components/Layout.js
  Sharky/src/pages/ContactUs.js
  Sharky/src/style.css
Labels: bug

#83 Update Sharky_Sprint4_meeting12_Nov22.md
  Meeting Minutes/Sharky_Sprint4_meeting12_Nov22.md
Labels: documentation

#69 Rename Sharky_Sprint3_meeting11_Nov14.md to Sharky_Sprint4_meeting11_…
  Meeting Minutes/Sharky_Sprint4_meeting11_Nov14.md
Labels: documentation

#90 Update SignUp.test.js
  Sharky/src/test/SignUp.test.js
Labels: documentation

#95 Update TeamManagement.test.js
  Sharky/src/test/TeamManagement.test.js
Labels: documentation

#94 Update Profile.test.js
  Sharky/src/test/Profile.test.js
Labels: documentation

#93 Update ShowTeams.test.js
  Sharky/src/test/ShowTeams.test.js
Labels: documentation

#92 Update HandleTeams.test.js
  Sharky/src/test/HandleTeams.test.js
Labels: documentation

#88 Update assessment.test.js
  Sharky/src/test/assessment.test.js
Labels: documentation

#87 Update CourseEvaluationResult.test.js
  Sharky/src/test/CourseEvaluationResult.test.js
Labels: documentation

#91 Update ConceptualAssessment.test.js
  Sharky/src/test/ConceptualAssessment.test.js
Labels: documentation

#96 Update WorkEthicAssessment.test.js
  Sharky/src/test/WorkEthicAssessment.test.js
Labels: documentation

#100 Acceptance Test for the ContactUs component. Fixes #99
  Sharky/src/pages/ContactUs.js
  Sharky/src/test/ContactUs.test.js
Labels: test

#98 Acceptance Test for the Dashboard component. Fixes #97
  Sharky/src/test/Dashboard.test.js
Labels: test

#102 AT-18: Acceptance test for Layout.js
  Sharky/src/test/Layout.test.js
Labels: test

#104 AT-19: Acceptance Test for DateTime.js
  Sharky/src/test/DateTime.test.js
  Sharky/src/test/Layout.test.js
Labels: test

#106 AT-6: Improvement to the test coverage of ShowTeams.test.js
  Sharky/src/test/ShowTeams.test.js
Labels: test

#109 Create Sharky_Sprint4_meeting14_Nov24.md
  Meeting Minutes/Sharky_Sprint4_meeting14_Nov24.md
Labels: documentation

#112 Add Acceptance Test for CourseEvaluation Component.
  Sharky/src/test/CourseEvaluation.test.js
Labels: test

#114 Adding Date/Time component to the profile page
  Sharky/src/App.js
Labels: enhancement
